Fix fatal (#56)
* removed all instances of Fatal/Fatalf

* added extra CI step

* fixed issue with check_fatal

* merged all CIs into one file, and seperated each step by name

* removed older CI yml file

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -22,5 +22,23 @@ jobs:
     - name: Build
       run: go build -v ./...
 
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+    - uses: actions/checkout@v4
     - name: Test
       run: go test -vet=off -v ./...
+
+  check:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+    - uses: actions/checkout@v4
+    - name: Check for usage of fatal in source
+      run: |
+        set -e
+        if find -name "*.go" -exec grep -Hn "Fatal" {} +; then
+            echo "::error ::Found disallow Fatal*() calls"
+            exit 1
+        fi
